### PR TITLE
Update config.m3u

### PR DESCRIPTION
**Pull request by dp247**

### CODE REVIEW

**Comment by ExperiencersInternational** [comment]
apologies for me not being active here btw

**Comment by ExperiencersInternational** [comment]
has Sky Arts turned into Sky Mix? 

Apologies in advance but I may remove the Sky channels, just because they seem to be quite persistent with takedowns for stuff (even for stuff originally free to air)

**Comment by ExperiencersInternational** [comment]
Amazing amount of selection you've added though btw

**Comment by dp247** [comment]
> has Sky Arts turned into Sky Mix?
> 
> Apologies in advance but I may remove the Sky channels, just because they seem to be quite persistent with takedowns for stuff (even for stuff originally free to air)

I don't know whether it's replaced, but I'd supposed to be a new free-to-air one. No worries if you wanna yeet it though. I'm probably going to maintain a more stripped-down version anyhow.


> Amazing amount of selection you've added though btw

Hehe, cheers. I was originally going to contribute to another project, but they prefer not to have timeshift channels, whereas I don't mind.

**Comment by ExperiencersInternational** [comment]
Thought it was quickly worth noting that subtitles work on some additional channels, tested Channel 4 quickly, couldn't get ITV1 working and it has subtitles now

**Comment by ExperiencersInternational** [comment]
Looked into Sky Mix, replaces Pick apparently

No clue where Sky Arts is now

I'm also struggling with getting ITV4 working but I don't think I gave that enough patience.

Either way, having more subtitles on certain channels is certainly helpful!

**Comment by ExperiencersInternational** [comment]
Just been browsing a bit more and do you know whether the streams are taken from Sky Stream or something? Publisher fields for ITV2 and Channel 4+1 show BSkyB as the publisher lol

image

**Comment by dp247** [comment]
It's possible, but I haven't looked into it. I assumed it was the Astra software passing in the metadata.

**Comment by ExperiencersInternational** [comment]
> The channels are likely fetched over satellite, found an open Astra server and contributed it to [Free-TV/IPTV#401](https://github.com/Free-TV/IPTV/pull/401)

Might have to take some of the stuff you've added there and make it available here since I'm not sure whether STV etc still works and we could always do with some additional channels like UTV

Thank you for the additional information btw

**Pull request merged**
