### PR TITLE
Update config.m3u

### PR DESCRIPTION
**Pull request by dp247**
- Reorder to fit Freeview EPG
- Add some missing channels
- Update BBC radio streams to newer HLS, as others will be discontinued this year
- Add some TVG images

### CODE REVIEW

**Comment by ExperiencersInternational** [comment]
Will merge but I'm not entirely sure every channel (e.g. 5USA and Dave-ju-vu) was migrated, but the radio improvements are pretty useful.

Thank you!

**Comment by dp247** [comment]
You're welcome!

I've also got some suggestions for extra 800s channels to boost the EPG, if they're any good? I can either open another PR or post them here lol

**Comment by ExperiencersInternational** [comment]
Post the information here if you want

They just have to be ones that are free to air, since the last thing I want to do is get sued

**Comment by dp247** [comment]
I didn't forget - I typed out a whole list then Windows got in the way :(
Anyways, I've left out the channels from Plex/Pluto/SamsungTV+ and gone with purely free to air networks:

- CNN: https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
- euronews: https://stream.ads.ottera.tv/playlist.m3u8?network_id=2571
- Bloomberg: https://bloomberg.com/media-manifest/streams/eu.m3u8
- Bloomberg Quicktake: https://bloomberg.com/media-manifest/streams/qt.m3u8
- ABC News Live: https://abcnews-streams.akamaized.net/hls/live/2023560/abcnews1/master.m3u8
- CBS News Live: https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8
- NBC News Now: http://nbcnews2.akamaized.net/hls/live/723426-b/NBCNewsPlaymaker24x7Linear99a3a827-ua/master.m3u8
- NHK World Japan: https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp-en/index_1M.m3u8
- TRT World HD: https://tv-trtworld.live.trt.com.tr/master.m3u8
- NDTV 24x7: https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/master.m3u8
- Arirang (Korea): https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8
- KBS World (Korea): https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/master.m3u8
- Edgesport: https://edgesports-sportstribal.amagi.tv/playlist.m3u8
- SportyStuff TV UK: https://ayozat-live.secure2.footprint.net/egress/bhandler/ayozat/sportystufftv/playlist.m3u8
- NASA TV Education (USA): https://uplynkcontent.sinclairstoryline.com/channel/ddd76fdc1c0a456ba537e4f48e827d3e.m3u8
- NASA TV Media (USA): https://ntv2.akamaized.net/hls/live/2013923/NASA-NTV2-HLS/master.m3u8
- NASA TV UHD (USA): https://endpnt.com/hls/nasa4k60/playlist.m3u8
- Daystar TV (USA): https://hls-live-media.cdn01.net/dvr/stream_37099_1.m3u8

**Comment by ExperiencersInternational** [comment]
Willing to add euronews and CNN but not sure about everything else, thank
you!

**Pull request merged**
