### PR TITLE
Update News channels

### PR DESCRIPTION
**Pull request by dp247**
- Some reordering
- Add in Al-Jazeera again
- Add Sky News, GB News and Newsmax

### CODE REVIEW

**Comment by ExperiencersInternational** [comment]
Probably worth me reordering STV if that still works

I mostly watch YouTube these days lol

**Comment by dp247** [comment]
Feel free to fork [this](https://github.com/dp247/YouTubeToM3U8) if you ever want YT Live streams ;)

**Comment by ExperiencersInternational** [comment]
> Feel free to fork [this](https://github.com/dp247/YouTubeToM3U8) if you ever want YT Live streams ;)

you've done a lot of work on that I see lol

**Comment by dp247** [comment]
I can't claim credit for all of it haha

**Pull request merged**
